### ISSUE TITLE
How many flags can it support

### ISSUE THREAD

**Issue by owain68** [pjb3/has-bit-field#1]
On mysql or sqlite.

**Comment by pjb3** [comment]
The field has to be numeric, so it depends on the largest number the field can hold.  For mysql it would be:

tiny int signed 7
tiny int unsigned 8
smallint signed 15
smallint unsigned 16
mediumint signed 23
mediumint unsigned 24
int signed 31
int unsigned 32
bigint signed 63
bigint unsigned 64

**Comment by owain68** [comment]
So bigint unsigned will give me the most "room for growth".  Great plugin.  Looking at the code it is very nice indeed.  Thanks.

**Comment by pjb3** [comment]
Sure, I've been just using INTEGER(10) for the bit field columns, which will hold 32-bits, which is way more than I'm using or would recommend using.  If you have the need for a lot of bits, you might want to break it up into multiple bit fields, rather than one bit field with 50 bits or more.
