### ISSUE TITLE
Adding new flags

### ISSUE THREAD

**Issue by owain68** [pjb3/has-bit-field#2]
The flag order must be relevant so when we add a new flag, all existing rows are "false" although logically they are null but I can live with that.

**Comment by pjb3** [comment]
As long as you add new flags to the end of the list, it will "just work".  There are no false or null values in the database.  It's stored as one numeric value in one column for each row.  When you add new flags, they will all be logically false, because those bits aren't on in any existing values.

**Comment by owain68** [comment]
args.each_with_index determines the bit order.  It might be worth putting a warning in the documentation to stress the importance of order and perhaps mention that the existing rows will all evaluate false for the new flag.

Cheers.

O.

**Comment by pjb3** [comment]
Yes, that's a very good idea.  If you could create a patch for that, I would apply it.

**Comment by owain68** [comment]
Patch emailed out to you.
