### ISSUE TITLE
Behaviour makes ActiveRecord validations tricky

### ISSUE THREAD

**Issue by owain68** [pjb3/has-bit-field#3]
class Tick < ActiveRecord::Base
    has_bit_field :bitmap, :apples, :oranges, :lemons, :melons
    validates_presence_of :name
    validate :must_have_one_citrus

```
def must_have_one_citrus
  oranges? || lemons?
end
```

  end

But when I go through the console I can see that the flags for new ActiveRecord objects are not available.

```
owain@/Users/owain/dev/sandpit$ script/console
Loading development environment (Rails 2.3.8)
>> t = Tick.new(:name => 'Owain')
+-------+--------+------------+------------+
| name  | bitmap | created_at | updated_at |
+-------+--------+------------+------------+
| Owain |        |            |            |
+-------+--------+------------+------------+
1 row in set
>> t.oranges?
=> true
>> t.save
  Tick Create (0.6ms)   INSERT INTO "ticks" ("name", "created_at", "updated_at", "bitmap") VALUES('Owain', '2010-08-03 13:05:21', '2010-08-03 13:05:21', NULL)
=> true
>> t.oranges?
=> true
>> t.lemons = true
=> true
>> t.oranges?
=> false
>> t
+----+-------+--------+-------------------------+-------------------------+
| id | name  | bitmap | created_at              | updated_at              |
+----+-------+--------+-------------------------+-------------------------+
| 8  | Owain | 4      | 2010-08-03 13:05:21 UTC | 2010-08-03 13:05:21 UTC |
+----+-------+--------+-------------------------+-------------------------+
1 row in set
>>
```

Is this the expected behaviour.  I would expect that t.oranges?  would return nil and hence fail validation on object creation.  Or perhaps false but certainly not true.

O.

**Comment by pjb3** [comment]
I think the bitfield column in the database needs to have a default value of 0.  That's another thing we need to add to the docs.  Try that out though and see if it fixes your problem.

**Comment by pjb3** [comment]
I just pushed version 0.3.1, which makes it so that it will work as you expect with or without a default value of 0 on the column.

**Comment by owain68** [comment]
I was using 0.2.2 since that was the last version on Github.  I will update README to point to Gemcutter.

**Comment by owain68** [comment]
emailing patch for README.md

**Comment by owain68** [comment]
Built some additional tests for validates_acceptance_of AR validation helper and I cannot get them to run.  I have emailed them through as a patch but here they are too.

```
  ActiveRecord::Base.connection.create_table(:skills) do |t|
    t.integer :outdoor_bit_field
    t.integer :indoor_bit_field, :default => 0
  end

  class Skill < ActiveRecord::Base
    extend HasBitField
    #attr_accessor :bit_field
    has_bit_field :outdoor_bit_field, :chops_trees, :builds_fences, :cuts_hedges
    has_bit_field :indoor_bit_field, :plays_piano, :mops_floors, :makes_soup

    validates_acceptance_of :chops_trees, :message => "You have to be a lumberjack"
    validates_acceptance_of :plays_piano, :message => "You must be a pianist"

  end  
  def test_ar_validations_no_default
    s = Skill.new(:plays_piano => true, :builds_fences => true, :cuts_hedges => false)

    assert !s.chops_trees?
    assert_nil s.chops_trees
    assert s.builds_fences?
    assert !s.cuts_hedges?
    assert !s.cuts_hedges    

    assert !s.valid?
    assert s.errors.on(:chops_trees)

    s.chops_trees = false
    assert !s.chops_trees?
    assert !s.valid?
    assert s.errors.on(:chops_trees)

    s.chops_trees = true
    assert s.chops_trees?
    assert s.valid?
    assert !s.errors.on(:chops_trees)
    assert s.save
  end
  def test_ar_validations_with_default
    s = Skill.new(:chops_trees => true, :mops_floors => true, :makes_soup => false)

    assert !s.plays_piano?
    assert_nil s.plays_piano
    assert s.mops_floors?
    assert !s.makes_soup?
    assert !s.makes_soup

    assert !s.valid?
    assert s.errors.on(:plays_piano)

    s.plays_piano = false
    assert !s.plays_piano?
    assert !s.valid?
    assert s.errors.on(:plays_piano)

    s.plays_piano = true
    assert s.plays_piano?
    assert s.valid?
    assert !s.errors.on(:plays_piano)
    assert s.save
  end
```

The test currently fails on 
    s.errors.on(:chops_trees)

This would be very helpful since I expect we would want to be able to validate and report back errors on checkboxes.

**Comment by owain68** [comment]
I think this is asking rather a lot of this great gem but my application I would like the model to look same to AV and AC irrespective of the underlying implementation.  

```
errors.add(:mops_floors, "Lumberjacks do not mop floors") if chops_trees?
```

But this approach is building a whole load of dependencies on AR which may or may not be a good thing?

Thanks for your time.

**Comment by pjb3** [comment]
It already depends on AR, so that's no problem.  I'll see what it would take to make the validations work.

**Comment by pjb3** [comment]
Take a look at README and the tests in 0.3.2.  To make it work, you are going to have to put your validates_acceptance_of calls ahead of the has_bit_field calls.  AR is being a little wonky be checking the database columns but not calling responds_to?, IMHO, so you have to work around that.

**Comment by owain68** [comment]
Did you manage to review the additional README.md patch I emailed you to pick up the correct version from gemcutter?
