### ISSUE TITLE
README.md update gem repository

### ISSUE THREAD

**Issue by owain68** [pjb3/has-bit-field#4]
Paul,

Thanks for the upates, everything works a treat now.  I was going to post something on Ruby Talk so you get some more users.  However, on the README it still points to the github gem repository which is now defunct.  See http://gems.github.com/  And from the list on http://gems.github.com/list.html you can see that the last version available is

```
pjb3-has-bit-field (0.2.2)
```

If you change the line in environment.rb
    config.gem "pjb3-has-bit-field", :lib => "has-bit-field", :source => "http://gems.github.com"
to
    config.gem "has-bit-field", :source => "http://gemcutter.org"

you get the current version.  I am not sure how the gem build service works behind the scenes but it does seem to work.

**Comment by pjb3** [comment]
This has been fixed
