### ISSUE TITLE
bootstrapping has_many_bits expects column to exist already

### ISSUE THREAD

**Issue by choxi** [pjb3/has-bit-field#7]
This gem causes an issue in Rails when you run rake db:migrate. When you call has_bit_field, these lines:
      if(respond_to?(:named_scope))
        if columns_hash[bit_field_attribute.to_s].null
          class_eval %{
            named_scope :#{field}, :conditions => ["#{table_name}.#{bit_field_attribute} IS NOT NULL AND (#{table_name}.#{bit_field_attribute} & ?) != 0", #{field}_bit]
            named_scope :not_#{field}, :conditions => ["#{table_name}.#{bit_field_attribute} IS NULL OR (#{table_name}.#{bit_field_attribute} & ?) = 0", #{field}_bit]  
          }
        else
          class_eval %{
            named_scope :#{field}, :conditions => ["(#{table_name}.#{bit_field_attribute} & ?) != 0", #{field}_bit]
            named_scope :not_#{field}, :conditions => ["(#{table_name}.#{bit_field_attribute} & ?) = 0", #{field}_bit]
          }
        end
      end
raise an error if the migration to add the column has not been run yet. Since rake db:migrate loads the Rails environment, you can't even run the migration because has_bit_field blows up if the column doesn't already exist. The only way to do it is to run the migration before you add has_bit_field to your model.

**Comment by pjb3** [comment]
Fixed in SHA ea7386c78479898d522052b3f556dc0c0668150f
